export enum ACCOUNT_PROVIDER {
    XERO = "XERO",
    MYOB = "MYOB",
};

export enum LOAN_APPLICATION_STATUS {
    INITIATED = 0,
    REVIEW_PENDING = 1,
    SUBMISSION_PENDING = 2,
    FINALISED = 3
};

export enum DROPDOWN_TYPE {
    ACCOUNT_PROVIDER = 1,
    BUSINESS_DETAIL = 2,
    YEAR_SELECTION = 3
};

export enum INPUT_TYPE {
    BUSINESS_DETAIL_NAME = 1,
    BUSINESS_DETAIL_SUMMARY = 2,
};

export enum APP_ERROR {
    // SA - server action
    SA_LOAN_INITIATE = "SA_LOAN_INITIATE_ERROR", 
    SA_LOAN_UPDATE = "SA_LOAN_UPDATE_ERROR",
    SA_LOAN_UPDATE_PARAM = "SA_LOAN_UPDATE_PARAM_ERROR",
    SA_LOAN_REVIEW = "SA_LOAN_REVIEW_ERROR",
    SA_LOAN_REVIEW_FETCH = "SA_LOAN_REVIEW_FETCH_ERROR",
    SA_LOAN_REMOVE = "SA_LOAN_REMOVE_ERROR",

    SA_BUSINESS_DETAIL_CREATE = "SA_BUSINESS_DETAIL_CREATE_ERROR",
    SA_BUSINESS_DETAIL_UPDATE_PARAM = "SA_BUSINESS_DETAIL_UPDATE_PARAM_ERROR",
    SA_BUSINESS_DETAIL_UPDATE = "SA_BUSINESS_DETAIL_UPDATE_ERROR",
    SA_BUSINESS_DETAIL_REMOVE = "SA_BUSINESS_DETAIL_REMOVE_ERROR",
    
    DECISION_SERVER = "DECISION_SERVER_ERROR",
}